### ISSUE TITLE
Scapture 페이지 레이아웃 리뉴얼

### ISSUE THREAD

**Issue by xogk1128** [Scapture-Hackaton/Scapture-Client#132]
### ⚠️Issue

- Scapture 페이지 레이아웃 리뉴얼한다.

### ✏️Task

- [x] 검색 버튼 디자인 변경
- [x] 구장 item 디자인 변경
- [x] 도시, 지역 레이아웃 변경

### 🗓Next Task

- [x] x
